name: Fodor Photography
favicon: null
layout_spectrum: 0.5054217500146478
typography_spectrum: 0.8355008822400123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.11380773689597845
  lightness: 0.04475206579081714
  saturation: 0.671332809375599
  rhythmicContrast: 0.014386574504896998
purpose: []
